# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.7.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
